### PR TITLE
Typescript types

### PR DESCRIPTION
**Pull request by rtrvrtg**
First pass at adding Typescript types for parse function and all input & output types.

I know that adding the `package-lock.json` might be extraneous to your requirements; if so, I'll take it out. Let me know if you have any other feedback. Thanks for your time involved in building and maintaining this package.

### CODE REVIEW

**Comment by nepsilon** [comment]
Hi, thanks for your PR. I'm not familiar with TypeScript. Is your PR adding new features? Could you document what changed usage-wise in the README file too? Thanks.

**Comment by rtrvrtg** [comment]
Hi, the PR doesn't really add any new features aside from providing type definitions for the parser function, as well as its inputs and outputs. This would make it easier to use search-query-parser inside any Typescript application without having to treat everything as the `any` type and having to guess from there about what it's done.
Here's a brief SO doc about what the type annotations do: https://stackoverflow.com/a/21247316

If you're not sure about all this, I'm happy to split the types out into a separate package and eventually submit it to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). That way, the types would be available, but optional.

**Comment by nepsilon** [comment]
Merged and published as `1.4.2`. Thanks @rtrvrtg for your PR.

**Comment by rtrvrtg** [comment]
@nepsilon You're welcome, thanks for your review. I'll put this version in use on our project; let me know if there are any bugs or issues relating to the types.

**Pull request merged**
