### PR TITLE
Do not split on spaces inside simple and double quotes

### PR DESCRIPTION
**Pull request by Gringill**
Use a regex to identify search terms more reliably than splitting on a space.
Does NOT respect escaping simple or double quotes within a term since JS
does not support look-behinds in regexs.

### CODE REVIEW

**Comment by Gringill** [comment]
Was a bit hasty in pull requesting this - should have held off until I found a substitute for lookbehinds in JS. A fix for this issue isn't really feasible until respecting escaped characters is accounted for.

**Comment by nepsilon** [comment]
Hi @Gringill, and thanks for your pull-request!

It looks all good to me, but could you add test cases to ensure future code addition won't break it?
The tests are put in here: https://github.com/retraceio/search-query-parser/blob/master/test/test.js

Thanks in advance!

**Comment by Gringill** [comment]
Added two tests... finally.

**Comment by nepsilon** [comment]
Thanks @Gringill. Looks great :+1:

**Pull request merged**
