### PR TITLE
Don't split on commas in quotes. https://github.com/nepsilon/search-q…

### PR DESCRIPTION
**Pull request by bradvogel**
…uery-parser/issues/16

### CODE REVIEW

**Comment by nepsilon** [comment]
We'd need at least one test case for each of these:

`from:one,two` -> `from: ["one", "two"]`
`from:one\,two` -> `from: ["one, two"]`
`from:"one,two"` -> `from: ["one, two"]`
`from:"one\,two"` -> `from: ["one, two"]`
`from:"one","two\, three"` -> `from: ["one" ,"two, three"]`

**Comment by bradvogel** [comment]
In order to support all those cases, some significant refactoring is required. Any chance you could merge this as a small improvement, and then we can work on the refactor after? It'll take some time.

**Comment by nepsilon** [comment]
Okey. We can merge this but can't release a new package before testing to be exhaustive.

You can go ahead an merge this yourself I think. I invited you as a contributor last week.
Please add an issue to keep track of these tests to be written. Thanks!

**Comment by bradvogel** [comment]
Ok, no problem, I'll keep this unmerged for now until I can write the tests.

**Comment by bradvogel** [comment]
Just a heads up that we ended up writing a new parser and releasing it here: https://github.com/mixmaxhq/search-string (cc @mericsson ).

**Pull request closed without merging**
